language: python
python: 3.4
sudo: false
env:
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py32-django17
  - TOXENV=py32-django18
  - TOXENV=py33-django17
  - TOXENV=py33-django18
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=docs
  - TOXENV=lint
install:
  - pip install tox
script:
  - tox -e $TOXENV
