language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - TOXENV=py26-14
  - TOXENV=py26-15
  - TOXENV=py26-16
  - TOXENV=py27-14
  - TOXENV=py27-15
  - TOXENV=py27-16
  - TOXENV=py27-17
  - TOXENV=py32-15
  - TOXENV=py32-16
  - TOXENV=py32-17
  - TOXENV=py33-15
  - TOXENV=py33-16
  - TOXENV=py33-17
  - TOXENV=py34-15
  - TOXENV=py34-16
  - TOXENV=py34-17
install:
  - pip install tox
script:
  - tox -e $TOXENV
